email: hmafsar9@gmail.com
password: MacartoLeads123

disableAntiLock: False

remote: True
hybrid: True 

experienceLevel:
 internship: False
 entry: False
 associate: False
 mid-senior level: True
 director: True
 executive: True

jobTypes:
 full-time: True
 contract: True
 part-time: False
 temporary: True
 internship: False
 other: True
 volunteer: False

date:
 all time: False
 month: True
 week: False
 24 hours: False

positions:
 - Machine Learning Engineer
 - Data Scientist
 - 
 #- ...
locations:
 - United Kingdom
 - United Kingdom
 - Hybrid
 - Remote
distance: 100

outputFileDirectory: C:\Users\hmafs\OneDrive\Desktop\EasyApplyBot-master\Resume-Hamza-Mahmood\output

companyBlacklist:
 #- company
 #- company2

titleBlacklist:
 #- word1
 #- word2

posterBlacklist:
 #- name1
 #- name2

uploads:
 resume: C:\Users\hmafs\OneDrive\Desktop\EasyApplyBot-master\Resume.pdf

 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: True
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting to this job's location? (yes/no checkbox)
 commute: True
 # Are you comfortable working in a remote environment? (yes/no checkbox)
 remote: True
 # Are you comfortable taking a drug in accordance with local/state laws? (yes/no checkbox)
 drugTest: True
 # Are you willing to complete an assessment? (yes/no checkbox)
 assessment: True
 # Have you completed the following level of education: DEGREE TYPE? (yes/no checkbox)
 degreeCompleted:
  - High School Diploma
  - Bachelor's Degree

  - Master's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: True

# ------------ Additional parameters: universityGpa ---------------
universityGpa : 4.0

# ------------ Additional parameters: salaryMinimum ---------------
salaryMinimum : 60000

# ------------ Additional parameters: languages ---------------
languages:
 english: Native or bilingual # None, Conversational, Professional, Native or bilingual

# ------------ Additional parameters: years of experience ---------------
# How many years of work experience do you have ...? (whole numbers only)
experience:
 # normal ones
 Accounting/Auditing: 0
 Administrative : 0
 Advertising : 0
 Analyst : 0
 Art/Creative: 0
 Business Development: 0
 Consulting: 6
 Customer Service: 0
 Distribution Design: 0
 Education: 0
 Engineering: 6
 Finance: 0
 General Business: 0
 Health Care Provider: 0
 Human Resources: 0
 Information Technology: 6
 Legal: 0
 Management: 0
 Manufacturing: 0
 Marketing: 0
 Public Relations: 0
 Purchasing: 0
 Product Management: 0
 Project Management: 6
 Production: 0
 Quality Assurance: 0
 Research: 0
 Sales: 0
 Science: 0
 Strategy/Planning: 0
 Supply Chain: 0
 Training: 0
 Writing/Editing: 0
 #python: 0
 #selenium: 0
 # default to put for any industry/skill that you did not list
 default: 6




 # default to put for any industry/skill that you did not list
 default: 6

# ------------ Additional parameters: personal info ---------------
personalInfo:
 First Name: Hamza
 Last Name: Mahmood
 Phone Country Code: United Kingdom (+44) # See linkedin for your country code, must be exact according to the international platform, i.e. Italy (+39) not Italia (+39)
 Mobile Phone Number: 07380178957
 Street address: Acton
 City: Luton # Include the state/province as well!
 State: Bedfordshire
 Zip: LU32DL
 Linkedin: 
 Website: # github/website is interchangeable here

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: Male
 race: None
 vetran: None
 disability: None
 citizenship: yes
 clearance: yes
